apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sockshop-ingress
  namespace: sock-shop
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - capstone.utibeokon.me
      secretName: letsencrypt-nginx-htnxv
  ingressClassName: nginx
  rules:
    - host: capstone.utibeokon.me
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: front-end
                port:
                  number: 80
    - host: prometheus.utibeokon.me
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: prom-kube-prometheus-stack-prometheus
                port:
                  number: 9090
    - host: grafana.utibeokon.me
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: prom-grafana
                port:
                  number: 80